### ISSUE TITLE
Single Click but Api called multiple time.

### ISSUE THREAD

**Issue by Janakz** [cartoonmangodev/react-boilerplate-redux-saga-hoc#29]
Hello @Visakeswaran @ChrissieFernando @chrissieaerospace .
I'm using this library: Implement successfully as mentioned in document.

All configuration done as Document suggest.
Api calling successfully 
But one strange issue : I faced last couple of days.
Every time user clicked on view: api called block execute one time.
But inside the reducer - got the same action event multiple time So My request api called multiple time.

I read the document, At Document I can't find any solution.
Also I checked your repo  regarding calling : but same issue.

At initial I got the single Action, Api registration in init HOC props.

So I request you please guide me.

PFA for Your reference.
Waiting for your response.
<img width="888" alt="Screenshot 2022-08-19 at 10 26 22 PM" src="https://user-images.githubusercontent.com/46066570/185669706-69e211a5-a941-48c7-a719-96d13b15c539.png">

Thanks
Zala.

**Comment by chrissieaerospace** [comment]
Hi @Janakz can you please share your code for reference

Thanks
Chrissie Fernando

**Comment by Janakz** [comment]
@ChrissieFernando :
Issue resolved:
Ref link :https://stackoverflow.com/questions/72626159/why-does-my-nextjs-code-run-multiple-times-and-how-can-this-be-avoided

Thanks
Zala
