### ISSUE TITLE
Getting an error which says "Middleware isn't a function". 

### ISSUE THREAD

**Issue by sj9710** [cartoonmangodev/react-boilerplate-redux-saga-hoc#9]
@chrissieaerospace According to documentation, I have created three files App.js, basic-example.js, and config.js and still, I am getting this error. I am using the latest version of Redux-Saga, is that an issue?

**Comment by sj9710** [comment]
Is this library is production ready?

**Comment by chrissieaerospace** [comment]
@sj9710 This Package doesn't support the latest version of redux-saga.Please install version redux-saga@0.16.2.

**Comment by sj9710** [comment]
@chrissieaerospace do you have any plans in the future to make this package compaitible with latest version of the redux saga?

**Comment by chrissieaerospace** [comment]
@sj9710  we are working on it.soon will give support for the latest version of redux-saga.
